{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ede33c83-8ee1-4fdf-809e-b673bc26036f",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "import boto3\n",
    "import sagemaker\n",
    "import sagemaker.session\n",
    "\n",
    "from sagemaker import utils\n",
    "from sagemaker.estimator import Estimator\n",
    "from sagemaker.inputs import TrainingInput, CreateModelInput, TransformInput\n",
    "from sagemaker.model import Model\n",
    "from sagemaker.transformer import Transformer\n",
    "\n",
    "from sagemaker.model_metrics import MetricsSource, ModelMetrics, FileSource\n",
    "from sagemaker.drift_check_baselines import DriftCheckBaselines\n",
    "from sagemaker.processing import (\n",
    "    ProcessingInput,\n",
    "    ProcessingOutput,\n",
    "    ScriptProcessor,\n",
    ")\n",
    "from sagemaker.sklearn.processing import SKLearnProcessor\n",
    "from sagemaker.workflow.conditions import ConditionLessThanOrEqualTo\n",
    "from sagemaker.workflow.condition_step import ConditionStep\n",
    "from sagemaker.workflow.functions import JsonGet\n",
    "\n",
    "from sagemaker.workflow.parameters import (\n",
    "    ParameterBoolean,\n",
    "    ParameterInteger,\n",
    "    ParameterString,\n",
    ")\n",
    "from sagemaker.workflow.pipeline import Pipeline\n",
    "from sagemaker.workflow.properties import PropertyFile\n",
    "from sagemaker.workflow.steps import (\n",
    "    ProcessingStep,\n",
    "    TrainingStep,\n",
    "    CreateModelStep,\n",
    "    TransformStep,\n",
    ")\n",
    "from sagemaker.workflow.model_step import ModelStep\n",
    "from sagemaker.workflow.pipeline_context import PipelineSession\n",
    "\n",
    "from sagemaker.workflow.execution_variables import ExecutionVariables\n",
    "from sagemaker.workflow.functions import Join\n",
    "from sagemaker.model_monitor import DatasetFormat, model_monitoring\n",
    "from sagemaker.clarify import BiasConfig, DataConfig, ModelConfig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2023c2bd-25d6-4fc8-bfd2-dd8ed0397549",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "region = sagemaker.Session().boto_region_name\n",
    "sm_client = boto3.client(\"sagemaker\")\n",
    "boto_session = boto3.Session(region_name=region)\n",
    "sagemaker_session = sagemaker.session.Session(boto_session=boto_session, sagemaker_client=sm_client)\n",
    "pipeline_session = PipelineSession()\n",
    "prefix = \"RegressionPredict\"\n",
    "\n",
    "role = sagemaker.get_execution_role()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "1be08b57-17c0-4859-8a15-58626eef0bff",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:botocore.credentials:Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole\n",
      "INFO:sagemaker:Creating processing-job with name ubuntu-ev-2023-05-22-17-10-43-136\n",
      "INFO:sagemaker.local.local_session:Starting processing job\n",
      "INFO:botocore.credentials:Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole\n",
      "INFO:sagemaker.local.image:No AWS credentials found in session but credentials from EC2 Metadata Service are available.\n",
      "INFO:sagemaker.local.image:docker compose file: \n",
      "networks:\n",
      "  sagemaker-local:\n",
      "    name: sagemaker-local\n",
      "services:\n",
      "  algo-1-fekor:\n",
      "    container_name: wdpc507eoj-algo-1-fekor\n",
      "    entrypoint:\n",
      "    - python3\n",
      "    - /opt/ml/processing/input/code/evidently.py\n",
      "    - --baseline\n",
      "    - s3://sm-dashboard-t/sagemaker-modelmonitor/train_headers/train_data_with_headers.csv\n",
      "    - --test\n",
      "    - s3://sm-dashboard-t/sagemaker-modelmonitor/test_data/test_data.csv\n",
      "    environment: []\n",
      "    image: ubuntu-ev\n",
      "    networks:\n",
      "      sagemaker-local:\n",
      "        aliases:\n",
      "        - algo-1-fekor\n",
      "    stdin_open: true\n",
      "    tty: true\n",
      "    volumes:\n",
      "    - /tmp/tmpivrkfqpj/algo-1-fekor/output:/opt/ml/output\n",
      "    - /tmp/tmpivrkfqpj/algo-1-fekor/config:/opt/ml/config\n",
      "    - /tmp/tmplfa8fetb:/opt/ml/processing/input/code\n",
      "    - /tmp/tmpivrkfqpj/shared:/opt/ml/shared\n",
      "version: '2.3'\n",
      "\n",
      "INFO:sagemaker.local.image:docker command: docker-compose -f /tmp/tmpivrkfqpj/docker-compose.yaml up --build --abort-on-container-exit\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating wdpc507eoj-algo-1-fekor ... \n",
      "Creating wdpc507eoj-algo-1-fekor ... done\n",
      "Attaching to wdpc507eoj-algo-1-fekor\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m /usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: evidently[test_suite] in /usr/local/lib/python3.6/dist-packages\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m \u001b[33m  evidently 0.2.1 does not provide the extra 'test_suite'\u001b[0m\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: dataclasses>=0.6 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: scikit-learn>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: statsmodels>=0.12.2 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Collecting PyYAML~=5.1 (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m   Downloading https://files.pythonhosted.org/packages/7a/5b/bc0b5ab38247bba158504a410112b6c03f153c652734ece1849749e5f518/PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640kB)\n",
      "\u001b[K    100% |################################| 645kB 2.1MB/s eta 0:00:01\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m \u001b[?25hRequirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: scipy>=1.5.4 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: plotly>=5.5.0 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.24.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.24.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.6/dist-packages (from statsmodels>=0.12.2->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=1.1.5->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=1.1.5->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.6/dist-packages (from plotly>=5.5.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from plotly>=5.5.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: idna<4,>=2.5; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from patsy>=0.5->statsmodels>=0.12.2->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->plotly>=5.5.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Installing collected packages: PyYAML\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m   Found existing installation: PyYAML 6.0\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m     Uninstalling PyYAML-6.0:\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m       Successfully uninstalled PyYAML-6.0\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Successfully installed PyYAML-5.4.1\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: evidently[test_suite] in /usr/local/lib/python3.6/dist-packages\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m \u001b[33m  evidently 0.2.1 does not provide the extra 'test_suite'\u001b[0m\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: dataclasses>=0.6 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: scikit-learn>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: statsmodels>=0.12.2 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Collecting PyYAML~=5.1 (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m   Using cached https://files.pythonhosted.org/packages/7a/5b/bc0b5ab38247bba158504a410112b6c03f153c652734ece1849749e5f518/PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: scipy>=1.5.4 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: plotly>=5.5.0 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.6/dist-packages (from evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.24.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.24.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.6/dist-packages (from statsmodels>=0.12.2->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=1.1.5->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=1.1.5->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.6/dist-packages (from plotly>=5.5.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from plotly>=5.5.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: idna<4,>=2.5; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from requests>=2.19.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from patsy>=0.5->statsmodels>=0.12.2->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->plotly>=5.5.0->evidently[test_suite])\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Installing collected packages: PyYAML\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m   Found existing installation: PyYAML 6.0\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m     Can't uninstall 'PyYAML'. No files were found to uninstall.\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Successfully installed PyYAML-5.4.1\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m   File \"/opt/ml/processing/input/code/evidently.py\", line 50, in <module>\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m     from functions import import_libs\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m   File \"/opt/ml/processing/input/code/functions.py\", line 10, in <module>\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m     import_libs()\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m   File \"/opt/ml/processing/input/code/functions.py\", line 7, in import_libs\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m     from evidently.test_suite import TestSuite\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor |\u001b[0m ModuleNotFoundError: No module named 'evidently.test_suite'; 'evidently' is not a package\n",
      "\u001b[36mwdpc507eoj-algo-1-fekor exited with code 1\n",
      "\u001b[0m1\n",
      "Aborting on container exit...\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Failed to run: ['docker-compose', '-f', '/tmp/tmpivrkfqpj/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit']",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/local/image.py\u001b[0m in \u001b[0;36mprocess\u001b[0;34m(self, processing_inputs, processing_output_config, environment, processing_job_name)\u001b[0m\n\u001b[1;32m    165\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 166\u001b[0;31m             \u001b[0m_stream_output\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    167\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mRuntimeError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/local/image.py\u001b[0m in \u001b[0;36m_stream_output\u001b[0;34m(process)\u001b[0m\n\u001b[1;32m    915\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mexit_code\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 916\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Process exited with code: %s\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0mexit_code\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    917\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Process exited with code: 1",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_20957/914015168.py\u001b[0m in \u001b[0;36m<cell line: 28>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     27\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 28\u001b[0;31m script_processor.run(\n\u001b[0m\u001b[1;32m     29\u001b[0m     \u001b[0mcode\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"evidently.py\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     30\u001b[0m     \u001b[0marguments\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"--baseline\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtrain_path\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"--test\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mtest_path\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/workflow/pipeline_context.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    282\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0m_StepArguments\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mretrieve_caller_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself_instance\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrun_func\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    283\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 284\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mrun_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    285\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    286\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/processing.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, code, inputs, outputs, arguments, wait, logs, job_name, experiment_config, kms_key)\u001b[0m\n\u001b[1;32m    665\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    666\u001b[0m         \u001b[0mexperiment_config\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcheck_and_get_run_experiment_config\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexperiment_config\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 667\u001b[0;31m         self.latest_job = ProcessingJob.start_new(\n\u001b[0m\u001b[1;32m    668\u001b[0m             \u001b[0mprocessor\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    669\u001b[0m             \u001b[0minputs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mnormalized_inputs\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/processing.py\u001b[0m in \u001b[0;36mstart_new\u001b[0;34m(cls, processor, inputs, outputs, experiment_config)\u001b[0m\n\u001b[1;32m    899\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    900\u001b[0m         \u001b[0;31m# Call sagemaker_session.process using the arguments dictionary.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 901\u001b[0;31m         \u001b[0mprocessor\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mprocess_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    902\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    903\u001b[0m         return cls(\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mprocess\u001b[0;34m(self, inputs, output_config, job_name, resources, stopping_condition, app_specification, environment, network_config, role_arn, tags, experiment_config)\u001b[0m\n\u001b[1;32m   1260\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_client\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate_processing_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1261\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1262\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_intercept_create_request\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess_request\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msubmit\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1263\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1264\u001b[0m     def _get_process_request(\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_intercept_create_request\u001b[0;34m(self, request, create, func_name)\u001b[0m\n\u001b[1;32m   5373\u001b[0m             \u001b[0mfunc_name\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mname\u001b[0m \u001b[0mof\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mfunction\u001b[0m \u001b[0mneeded\u001b[0m \u001b[0mintercepting\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   5374\u001b[0m         \"\"\"\n\u001b[0;32m-> 5375\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mcreate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   5376\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   5377\u001b[0m     def _create_inference_recommendations_job_request(\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36msubmit\u001b[0;34m(request)\u001b[0m\n\u001b[1;32m   1258\u001b[0m             \u001b[0mLOGGER\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Creating processing-job with name %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mjob_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1259\u001b[0m             \u001b[0mLOGGER\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"process request: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mjson\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdumps\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mindent\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1260\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_client\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate_processing_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1261\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1262\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_intercept_create_request\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess_request\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msubmit\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/local/local_session.py\u001b[0m in \u001b[0;36mcreate_processing_job\u001b[0;34m(self, ProcessingJobName, AppSpecification, ProcessingResources, Environment, ProcessingInputs, ProcessingOutputConfig, **kwargs)\u001b[0m\n\u001b[1;32m    127\u001b[0m         \u001b[0mprocessing_job\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_LocalProcessingJob\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcontainer\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    128\u001b[0m         \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Starting processing job\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 129\u001b[0;31m         processing_job.start(\n\u001b[0m\u001b[1;32m    130\u001b[0m             \u001b[0mProcessingInputs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mProcessingOutputConfig\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mEnvironment\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mProcessingJobName\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    131\u001b[0m         )\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/local/entities.py\u001b[0m in \u001b[0;36mstart\u001b[0;34m(self, processing_inputs, processing_output_config, environment, processing_job_name)\u001b[0m\n\u001b[1;32m    138\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0menvironment\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0menvironment\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    139\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 140\u001b[0;31m         self.container.process(\n\u001b[0m\u001b[1;32m    141\u001b[0m             \u001b[0mprocessing_inputs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprocessing_output_config\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0menvironment\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprocessing_job_name\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    142\u001b[0m         )\n",
      "\u001b[0;32m~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/local/image.py\u001b[0m in \u001b[0;36mprocess\u001b[0;34m(self, processing_inputs, processing_output_config, environment, processing_job_name)\u001b[0m\n\u001b[1;32m    169\u001b[0m             \u001b[0;31m# which contains the exit code and append the command line to it.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    170\u001b[0m             \u001b[0mmsg\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34mf\"Failed to run: {compose_command}\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 171\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    172\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    173\u001b[0m             \u001b[0;31m# Uploading processing outputs back to Amazon S3.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Failed to run: ['docker-compose', '-f', '/tmp/tmpivrkfqpj/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit']"
     ]
    }
   ],
   "source": [
    "\n",
    "baseline = ParameterString(\n",
    "    name=\"baseline\",\n",
    "    default_value=f\"s3://sm-dashboard-t/sagemaker-modelmonitor/train_headers/train_data_with_headers.csv\",\n",
    ")\n",
    "test = ParameterString(\n",
    "    name=\"test\",\n",
    "    default_value=f\"s3://sm-dashboard-t/sagemaker-modelmonitor/test_data/test_data.csv\",\n",
    ")\n",
    "\n",
    "image = '018079024734.dkr.ecr.us-east-1.amazonaws.com/evidently-image:latest'\n",
    "script_processor = ScriptProcessor(\n",
    "    image_uri='ubuntu-ev', # local image\n",
    "    command=[\"python3\"],\n",
    "    instance_type=\"local\",\n",
    "    instance_count=1,\n",
    "\n",
    "    role=role,\n",
    ")\n",
    "\n",
    "train_path = f\"s3://sm-dashboard-t/sagemaker-modelmonitor/train_headers/train_data_with_headers.csv\"\n",
    "test_path = f\"s3://sm-dashboard-t/sagemaker-modelmonitor/test_data/test_data.csv\"\n",
    "\n",
    "\n",
    "script_processor.run(\n",
    "    code=\"evidently.py\",\n",
    "    arguments=[\"--baseline\", train_path, \"--test\",test_path],\n",
    ")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_tensorflow2_p310",
   "language": "python",
   "name": "conda_tensorflow2_p310"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
